org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.128
neo_version_range=[21.1.0,)
loader_version_range=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mod_id=ugpaths
mod_name=Undergarden Paths
mod_license=MIT
mod_version=0.1.1
mod_group_id=xaidee
mod_authors=Xaidee Quartz
mod_description=An addon to the Undergarden that adds paths for the dimension's respective dirt/turf types.
