modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/VoidLeech/Undergarden-Paths/issues"
license="The MIT License (MIT)"

[[mods]]
modId="ugpaths"
version="${mod_version}"
displayName="Undergarden Paths"
# updateJSONURL=""
displayURL="https://modrinth.com/mod/undergarden-paths-repathed"
logoFile="Undergarden Paths.png"
logoBlur=false
itemIcon="ugpaths:deepsoil_path"
configuredBackground="undergarden:textures/block/deepsoil.png"
credits='''
Thanks goes to Quek for creating the amazing Undergarden mod!
'''
authors="Xaidee Quartz, VoidLeech"
description='''
An addon to the Undergarden that adds paths for the dimension's respective dirt/turf types.
'''

[[dependencies.ugpaths]]
modId="forge"
mandatory=true
versionRange="[47.1.99,48)"
ordering="NONE"
side="BOTH"

[[dependencies.ugpaths]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.ugpaths]]
modId="undergarden"
mandatory=true
versionRange="[0.8.14,)"
ordering="AFTER"
side="BOTH"
