modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/VoidLeech/Undergarden-Paths/issues/"
license="The MIT License (MIT)"

[[mods]]
modId="ugpaths"
version="${mod_version}"
displayName="Undergarden Paths"
# updateJSONURL=""
displayURL="https://modrinth.com/mod/undergarden-paths-repathed"
logoFile="Undergarden Paths.png"
logoBlur=false
itemIcon="ugpaths:deepsoil_path"
configuredBackground="undergarden:textures/block/deepsoil.png"
credits='''
Thanks goes to Quek for creating the amazing Undergarden mod!
'''
authors="Xaidee Quartz, VoidLeech"
description='''
An addon to the Undergarden that adds paths for the dimension's respective dirt/turf types.
'''

[[dependencies.ugpaths]]
modId="neoforge"
type="required"
versionRange="[20.4.167,20.5)"
ordering="NONE"
side="BOTH"

[[dependencies.ugpaths]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.20.5)"
ordering="NONE"
side="BOTH"

[[dependencies.ugpaths]]
modId="undergarden"
type="required"
versionRange="[0.8.15,)"
ordering="AFTER"
side="BOTH"
