modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/xaidee/Undergarden-Paths/issues/"
license="The MIT License (MIT)"

[[mods]]
modId="ugpaths"
version="${mod_version}"
displayName="Undergarden Paths"
# updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/undergarden-paths"
logoFile="Undergarden Paths.png"
logoBlur=false
itemIcon="ugpaths:deepsoil_path"
configuredBackground="undergarden:textures/block/deepsoil.png"
credits='''
Thanks goes to Quek for creating the amazing Undergarden mod!
'''
authors="Xaidee Quartz"
description='''
An addon to the Undergarden that adds paths for the dimension's respective dirt/turf types.
'''

[[dependencies.ugpaths]]
modId="neoforge"
type="required"
versionRange="[20.6.1-beta,21)"
ordering="NONE"
side="BOTH"

[[dependencies.ugpaths]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.ugpaths]]
modId="undergarden"
type="required"
versionRange="[0.8.17,)"
ordering="AFTER"
side="BOTH"
